#!/usr/bin/env php

<?php

// Applying composer autoload
include_once './vendor/autoload.php';

use Mohamed179\Core\CLI\CLI;
use Dotenv\Dotenv;
use Mohamed179\Core\CLIApplication;

// Getting env variables from .env file
$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->load();
$config = [
    'app_name' => $_ENV['APP_NAME'],
    'main_layout' => $_ENV['MAIN_LAYOUT'],
    'db' => [
        'host' => $_ENV['DB_HOST'],
        'port' => $_ENV['DB_PORT'],
        'user' => $_ENV['DB_USER'],
        'password' => $_ENV['DB_PASSWORD'],
        'database' => $_ENV['DB_DATABASE'],
    ],
    'userClass' => $_ENV['USER_CLASS']
];

// Creating new application
$app = new CLIApplication(__DIR__, $config);

// Running the cli
$cli = new CLI();
$cli->run($_SERVER['argv']);