#!/usr/bin/env php

<?php

// Applying composer autoload
include_once './vendor/autoload.php';

use Dotenv\Dotenv;
use App\Core\Application;

// Getting env variables from .env file
$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->load();
$config = $_ENV;

// Creating new application
$app = new Application(__DIR__, $config);

// TODO: build your cli
